### ISSUE TITLE
I cannot run the seed app on web, desktop. on iOs and android it gives a heap of errors

### ISSUE THREAD

**Issue by Channad** [jlooper/angular-starter#13]
Most of the time I am getting this error

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start.desktop"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! angular-starter@0.0.0 start.desktop: `gulp desktop && NODE_ENV=development electron ./dist/dev`
npm ERR! Exit status 1

I have recreated the project several times. Even to install I need to run the install npm command with "sudo"

However Ios installation ran without errors but output was buggy and did not run
Android ran on the emulator but gave a log of errors on missing scripts

I am attaching the desktop build error log here with.

Not sure where the problem is

my system is Mac with macOS Siera 10.12.4
node v 10.7.0
npm v 4.2.0
NativeScript v3.0
Angular v2.4.10/4.1.3 (platform server v 4.1.3 only)

I am new to all this so if there are any shortcomings pl let me know.
Thanks in advance

[2017-05-28T23_49_30_825Z-debug copy.txt](https://github.com/jlooper/angular-starter/files/1034623/2017-05-28T23_49_30_825Z-debug.copy.txt)

**Comment by jlooper** [comment]
I've decided to deprecate this seed in support of a new, better one: https://github.com/TeamMaestro/angular-native-seed

**Comment by Channad** [comment]
I figured that it was due to a problem with the instalation of Android SDK. The Android CLI has change significantly since most of the comments I found on these forums. Once I manualy set the $ANDROID_HOME and $PATH by using "sudo nano/etc/paths" and added the path to android home and tools/bin it worked. However the CLI sdkmanager did not work properly may be the way I specified the package was incorrect. However I could use the Adroide studio's SDKMANAGER UI to get API 22 installed. @jlooper even your suggestion to work it needed the above fixes. But to make things verse it lacked the documentation in a big way. It does not say you need to install the packages in both at root and in nativescript after installing the seed.
