### ISSUE TITLE
TypeScript compiler failed with exit code 1

### ISSUE THREAD

**Issue by Joeycz** [jlooper/angular-starter#2]
npm run start.android or npm run start.ios

TypeScript compiler failed with exit code 1
Sending exception report (press Ctrl+C to stop).........

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start.android"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! basic-web-mobile@0.0.0 start.android: `cd nativescript && tns emulate android`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the basic-web-mobile@0.0.0 start.android script 'cd nativescript && tns emulate android'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the basic-web-mobile package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd nativescript && tns emulate android
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs basic-web-mobile
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls basic-web-mobile
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/chengzheng/czpro/angular-starter/npm-debug.log

**Comment by jlooper** [comment]
I just updated the repo to the latest Angular. Please give it a try...took me a few times to run the app on Genymotion but it did eventually work.

**Comment by Joeycz** [comment]
After rebase your commit, all is ok, thanks!
