### ISSUE TITLE
Unable to create symlink

### ISSUE THREAD

**Issue by mike-morr** [jlooper/angular-starter#4]
**Steps to reproduce and a minimal demo of the problem**

Follow instructions from (https://jlooper.github.io/angular-starter/#prerequisites)

**Current behavior**

npm install fails with:

```
npm WARN angular-seed-advanced@0.0.0 No license field.
Configuring...
**A symlink already exists.**
------------------------ Angular Seed Advanced is Now Ready ----------------------------

Run your web app with:
  npm start

Run your Mobile app via NativeScript with:
  iOS:     npm run start.ios
  Android: npm run start.android

Run your Desktop app via Electron with:
  Mac:     npm run start.desktop
  Windows: npm run start.desktop.windows

-----------------------------------------------------------------------------------------

**We were unable to create a symlink**  - from -
   /Users/mike/Code/sp-surfer/src/client/app     - to - 
   /Users/mike/Code/sp-surfer/nativescript/src/app
If you don't create this symlink, you will have to manually copy the code each time you change it.
```

After this, running npm run ios.start crashes and burns.  Should one of the directories above be empty?

**Expected/desired behavior**

No errors.

**Other information**

macOS Sierra 10.12.3

**Comment by jlooper** [comment]
hi, I'm sorry for the late response. You can manually delete the symlinks (app and assets) and rebuild the project... in theory! Let me know if that works!

**Comment by NathanWalker** [comment]
All issues cleared here - best way to move forward:
* Just clone fresh and `npm i` from the root 👍
