### ISSUE TITLE
UNMENT PEER DEPENDENCY when adding platforms

### ISSUE THREAD

**Issue by cinjoff** [jlooper/angular-starter#5]
**Current behavior**
After cloning a clean version of the repo having npm packages installed,
running `tns platform add android/ios` does it's thing, but results with:

```
├── UNMET PEER DEPENDENCY @angular/compiler@2.4.10
├── UNMET PEER DEPENDENCY @angular/core@2.4.10
├── tns-ios@2.5.0
└── UNMET PEER DEPENDENCY webpack@2.2.0-rc.3
```

Despite that, it says `Project successfully created.` afterwards, which is still not giving me too much confidence

**Comment by NathanWalker** [comment]
All issues cleared here - best way to move forward:
* Just clone fresh and `npm i` from the root 👍
