### ISSUE TITLE
Update to Angular 4

### ISSUE THREAD

**Issue by cinjoff** [jlooper/angular-starter#7]
As of today (28 March), Nativescript supports the newly updated Angular 4 version.

Guidelines on how to update to it are posted here
https://www.nativescript.org/blog/nativescript-supports-angular-4

**To consider:**
angular animations are now a separate module, which means that they are optional. Considering that this project is in the "basic seed" nature, I am not sure if this dependency should be always be included. I think it'd be nice to have a 3 step process on how to extend the project with such features, but they shouldn't necessarily be included in the project. This opinion is from a person with little to no experience with Angular 2, so you find them essential, they could also be already included.

It'd be nice if somebody picks this up (could be me, if I find time in T + 24h from now).

**Comment by jlooper** [comment]
I just upgraded one of my projects, I think it won't be too awful to do this one
